version: "2"
linters:
  enable:
    - dupl
    - durationcheck
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - godot
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - revive
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    forbidigo:
      forbid:
        - pattern: ioutil\.
        - pattern: ^print.*$
    nakedret:
      max-func-lines: 1
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv|w\.Stop). is not checked
      - path: (.+)\.go$
        text: (G104|G307)
      - path: (.+)\.go$
        text: Potential file inclusion via variable
      - path: (.+)\.go$
        text: unused-parameter
      - path: (.+)\.go$
        text: if-return
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
